name: Fly Deploy
on:
  push:
    branches:
      - main    # 如果你的分支叫 master，请改成 master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 安装 Flyctl 工具
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      # 执行部署命令 (它会自动读取你仓库里的 fly.toml)
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
